spring:
  profiles:
    active:
    - dev
---

server:
  port:7001 #注册中心占用7001端口，冒号后面必须要有空格
  
spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka-client
    
euerka:
  instance:
    hostname: euerka7001.com
  client:
    register-with-euerka: false #当前的euerka-server自己不注册进服务列表中
    fetch-registry: false #不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka7001.com/euerka/
      
---

server:
  port:7001 #注册中心占用7001端口，冒号后面必须要有空格
  
spring:
  profiles: test
  application:
    name: microservicecloud-config-eureka-client
    
euerka:
  instance:
    hostname: euerka7001.com
  client:
    register-with-euerka: false #当前的euerka-server自己不注册进服务列表中
    fetch-registry: false #不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka7001.com/euerka/